
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Dec 29 03:12:52 CET 2018
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 18;
  public static final int GREATER_OR_EQUAL = 39;
  public static final int INCREMENT = 15;
  public static final int CONST = 25;
  public static final int CHAR = 28;
  public static final int ASTERISK = 21;
  public static final int SLASH = 22;
  public static final int NOT_EQUAL = 38;
  public static final int CONTINUE = 43;
  public static final int GREATER = 35;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int INTERFACE = 47;
  public static final int FOR = 41;
  public static final int MINUS = 20;
  public static final int DECREMENT = 16;
  public static final int LESSER_OR_EQUAL = 40;
  public static final int RPAREN = 7;
  public static final int AND = 34;
  public static final int OR = 33;
  public static final int BOOL = 29;
  public static final int COMMA = 8;
  public static final int CLASS = 44;
  public static final int LESSER = 36;
  public static final int PLUS = 11;
  public static final int IF = 31;
  public static final int IS_EQUAL = 37;
  public static final int DOT = 14;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int RBRACKET = 19;
  public static final int EQUAL = 12;
  public static final int NEW = 24;
  public static final int error = 1;
  public static final int PERCENT = 23;
  public static final int NUMBER = 27;
  public static final int BREAK = 42;
  public static final int IDENT = 30;
  public static final int VOID = 13;
  public static final int LBRACE = 3;
  public static final int ELSE = 32;
  public static final int ENUM = 26;
  public static final int READ = 17;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 45;
  public static final int PROG = 2;
  public static final int IMPLEMENTS = 46;
  public static final int PRINT = 9;
}

